development:
  database_host: 10.1.1.10
  database_username: admindb
  database_password: TqrpfXx3smAhVByG

test:
  database_host: 10.1.1.10
  database_username: admindb
  database_password: TqrpfXx3smAhVByG

production:
  database_host: <database-host>
  database_username: <database-username>
  database_password: <database-password>
